name: Lint and Test Charts

on:
  pull_request: # <--- When to Run this CI jobs
    branches: [ $default-branch ] # <--- Which Branch

jobs:
  lint-test: # <--- Test Type
    runs-on: ubuntu-latest # <--- virtual-environments
    steps:
      - name: Checkout # <--- Check out code from repo
        uses: actions/checkout@v2 # <---- Using public github action
        with:
          fetch-depth: 0 # <--- to fetch all history for all branches and tags


      - name: Set up Helm
        uses: azure/setup-helm@v1 # <---- Using public helm action
        with:
          version: v3.4.0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v8.4
        with:
          files: |
            charts/* 

      - name: Run helm lint
        if: steps.changed-files.outputs.any_changed == 'true' 
        run: helm lint charts
